### ISSUE TITLE
ArcGIS JavaScript API version 4.0

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#105]
@allisonmuise ,

After considering all enhancements we find it is easier to revamp CS Manager than to make changes in the existing code base. We can revamp either using ArcGIS JS API 3.15 or 4.0 beta 3. However, as 4.0 beta 3 is a framework change, upgrading from 3.15 to 4.0 will once again require a revamp and considerable efforts. And upgrading from 4.0 beta 3 to 4.0 final release is expected to be a small change compared with 3.15 to 4.0. To avoid multiple revamps and reduce overall efforts we suggest implementing the current CS Manager changes using 4.0 beta 3. 

Please let us know your inputs.

**Comment by allisonmuise** [comment]
@ScottOppmann @MikeTschudi What do you think? @MikeTschudi Am I remembering correctly that 4.0 won't support 2D?

**Comment by ScottOppmann** [comment]
@allisonmuise - I think the 4.0 API supports 2d and 3d but @MikeTschudi should confirm.  I don't believe webmaps are currently supported in the 4.0 API and we should confirm they will be in Beta 3 before proceeding down this road.  Also should recognize that we will be introducing additional risk building on the 4.0 API and may very well find other gaps as we get further in to development.

**Comment by MikeTschudi** [comment]
We're in 4.0 final release at this time--beta 3 is obsolete.  

4.0 has moderate support for 2D.  Abilities that we're used to such as editing, printing, searching feature layers using the Search widget, or zooming to a selected feature are not present in the first release.  The most important limitation for us is that it does not support webmaps at all; they may be moved up to as early as 4.1, but it's a big task because webmaps are so feature-rich.

The 4.0 API should not be used for 2D applications that will go into production before fall--maybe even later.

The 4.0 API is very different than the earlier versions.  I don't see it being used for anything but new applications--there's no way that we'll be able to port an older app to 4.0 without a rewrite.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : per the above comments, please build this Manager update on jsdev 3.16.
