### ISSUE TITLE
Using third party plugin for fixing table header while scrolling

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#117]
@allisonmuise

As recommended in the mockups, we are using the bootstrap bordered table with calcite css overrides for displaying the feature layer table. Currently when there are more features in the data viewer, vertical scroll bar appears. While scrolling it, table header also gets scrolled. To keep table header fix, we need to use this [StickyTableHeaders](https://github.com/jmosbech/StickyTableHeaders) plugin.
Please let us know if we can go ahead and use this.

**Comment by allisonmuise** [comment]
@MikeTschudi : After dev summit, could  you take a look at this and confirm that this is a plugin we can ship and use?

**Comment by MikeTschudi** [comment]
I believe that we can use it because it is identical to the [MIT license](https://opensource.org/licenses/MIT), which is [considered by Apache to be compatible](http://www.apache.org/legal/resolved.html#category-a).  We must include the copyright statement with the plugin to be compliant with the license.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please proceed
