### ISSUE TITLE
Default filter values on app load

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#133]
When filters are applied on app load, fields that have default filter values do not appear to have filters applied, even though only a subset of the data is visible in the table and map.

- Filter graphic is the white 'no filter applied' graphic
- no value shows in the filter box
- no option to clear the filter
- only 1 of 2 records visible (expected only when default filter applied)

![2016-04-13 3-13-48 pm](https://cloud.githubusercontent.com/assets/2752195/14511165/7d070e7c-018a-11e6-90fe-bfc4380da4a8.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We are unable to reproduce this issue.
Can you please share an app

--Pratik Gohil

**Comment by allisonmuise** [comment]
URL sent via email

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : were you able to reproduce the issue with the app sent via email?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Yes, we were able to reproduce this issue & will be fixed in upcoming code drop.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Now the default attribute values never seem to be applied. When enableFilter is true, I expect the map to load with the default filter values applied.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I can still reproduce this issue. If you are unable to repro, I will demo on the call this week.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

The last code drop we delivered included a fix for this issue. We verified that by seeing the filter was being applied on load correctly on the url you shared by email.

We are still investigating this as we are unable to reproduce this. Can you please share an app where filters are not being applied when `enablefilter=true`?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam The filter is being applied because no records are loading in the table, but the filter icon is white, not black, so it LOOKS like no filters are being applied. There is also no filter value shown in the filter dialog and the 'clear' button is disabled. 

This only happens on initial load, and I am using the code drop from ~8 days ago.

I do not have a URL to send, but I will show this in tomorrow's meeting.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We found the root cause of this issue. This is occurring with fields with domains [0:No, 1:YES] and the filter is set to [1:YES] and the layer does not have any features with value [1:YES].

The app was trying to fill up the dropdown with distinct values from the layer's field instead of directly displaying all the domain values. In this case, there were no features with [1:YES] in the layer, so the filter was applied, but the dropdown did not have an entry for [YES], so it defaulted to "Select" in the dropdown. This caused the inactive filter icon to display instead of the filter applied icon.

Please let us know if this makes sense.

The important point in the above explanation is that the app was filling up the dropdown with distinct values from the field instead of all the domain values.

We are evaluating if this is a low LOE and low risk fix. Will post an update soon.

**Comment by allisonmuise** [comment]
verified
