### ISSUE TITLE
Export selected rows to CSV

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#139]
to help integrate with other systems, it would be nice to be able to export selected rows from Manager to a csv file.

(Marshfield)

**Comment by allisonmuise** [comment]
ditto American Red Cross

**Comment by allisonmuise** [comment]
ditto Doral, FL (UC 2018)

**Comment by pratikg** [comment]
@allisonmuise,

We are planning to implement this enhancement as described below.

1. We would provide the export to CSV icon below the application header.

![image](https://user-images.githubusercontent.com/1454356/49586515-624e4d00-f987-11e8-954b-8dd10c96017b.png)


2. Initially, this icon will be disabled since no records would be selected.

3. On feature selection, this icon will be enabled.

4. On click of this icon, CSV file will be downloaded and success message will be displayed stating "CSV file downloaded".

5. Name of the CSV file will be the name of a layer.

6. CSV file will be downloaded in both the mode i.e; show all & show selected.

Please confirm should we go ahead and implement this enhancement?

**Comment by aparveen** [comment]
This is verified in devext.

**Comment by skrishn** [comment]
@aparveen added testcase
