### ISSUE TITLE
Option to view only selected records in table

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#151]

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We are planning to implement this functionality as shown below.

![picture1](https://cloud.githubusercontent.com/assets/2959186/16678336/b8bc4978-44fb-11e6-94ce-7eabc04e91b8.png)

Behaviour of the the functionality would be as described below :

1. Initially 'Selection options' icon would be disabled
2. On selecting feature 'Selection options' would be enabled
3. On clicking 'Show Selected', selected feature would be visible in the table & 'Show Selection' option would turned to 'Show All'.
4. On clicking 'Show All' option, all the feature would be visible in the table & 'Show All' option would turned to 'Show Selected'.
5. Since, multiple records are selected in 'Show Selected' mode, popup tab would be always in editable mode as per current functionality.
6. While editing(popup tab) in 'Show selected' mode, all the feature in this mode would be updated and displayed as selected.
7. Feature would be de-selected in 'Show Selected' mode by pressing ctrl key + selecting the selected feature.

Please let us know your thoughts on this.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@MikeMillerGIS : Do you need the 'Zoom to selected' as well?

**Comment by MikeMillerGIS** [comment]
I do not think so

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Your approach sounds good. Do you need me to get a selection graphic in a style that matches the others, or do you have one?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Since, map selection is also possible in 'Show Selected' mode. We are planning to implement this as described below

1. In show selected mode, if any record is selected from map(single click) than previous record will be de-selected from both map & grid. Newly selected record will only be displayed in map & grid.

2. In show selected mode, if multiple record is selected from map(via CTRL key) than records will be added in grid and displayed as selected.

Other areas :
1. In show selected mode search icon will be disabled like previous version of the manager app.
2. On refresh, all the selections are cleared hence show selected option will be removed & icon of selection option will be displayed in disabled state

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Sounds good!

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are planning to disable time slider in "Show Selected" mode. However, currently on multiple selection time slider gets disabled. So for both multiple selection or single selection followed by "Show Selected" mode time slider will be disabled.

Please let us know your thoughts on this.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Should we provide small carot icon beside "Selection Option" icon like previous version of manager  app as shown below or just keep "Selection Option" icon ?

![image](https://cloud.githubusercontent.com/assets/2959186/17175104/4168a3f8-5423-11e6-9ea9-94d54ebf2e22.png)


--Pratik Gohil

**Comment by allisonmuise** [comment]
Yes, please keep the arrow to indicate the presence of a drop-down list

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have one more query regarding disabling of time slider which is described above. Could you also provide your feedback on that.

--Pratik Gohil

**Comment by allisonmuise** [comment]
Sorry, Pratik! Yes, that makes sense to me.

**Comment by allisonmuise** [comment]
verified
