### ISSUE TITLE
MP4 attachments not show in media carousel

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-manager#154]
If possible, can the videos be shown in the media panel?

**Comment by MikeMillerGIS** [comment]
@CTLocalGovTeam @allisonmuise Is this by design or a bug?

**Comment by allisonmuise** [comment]
@MikeMillerGIS : In the design we only requested images and charts in the media panel. I wasn't aware that video support had been added to AGOL

**Comment by MikeMillerGIS** [comment]
ok, changed label to enhancement

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @MikeMillerGIS, @ScottOppmann

We are analysing this enhancement and will keep you updated.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have found an issue with mp4 attachments during our testing.

Issue:
MP4 attachments are unable to play in IE9, iPad & Tab. This is an issue with only mp4 videos as attachments. MP4 videos that are presented as links in field values work fine across all browsers & devices.

Steps to reproduce:
1 Add mp4 attachment to a feature 
2 Add mp4 video link to the any field in the layer
3 Launch the application(in IE9/iPad/Tab)
4 Click on the feature in which attachment is added
5 Click on media panel
6 Observe that video panel is displayed with a cross icon which denotes that video is unable to play
7 Go to next item in media panel & observe that the video that was added as a link is playable

We think this is an issue in the way acrgis server provides the output when a video attachment is served out by arcgis server. We see there is a difference in http headers, most notably 'Content-Range', 'Accept-Ranges' are absent in the response. These headers are required so that browsers can start playing the file without fully downloading the file. We dont know for sure how the modern browsers are able to play this file correctly.

Here is a link that explains similar issue
http://stackoverflow.com/questions/10511006/html5-video-not-working-on-ipad

Here is safari documentation that clearly states the required http headers for video files.
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6






 
Please share your thoughts.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

This build addresses the original Mp4 issue. However, it does not address the above known issue of attachments - unable to play in IE9, iPad, Tab.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

Pratik - I am able to repro this on iPads, even from the web map, but I can't repro on android tablets. Can you send me the details on what was tested for Android? 

Chrome or Android browser? Browser version? OS version?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Apologies. It does work on android tablet. However, the video is extremely slow to load. The video is playable after 3-4 mins. Do you also see similar behavior?
We are testing this on a Samsung Tab with `Chrome 51.0.2704.81` on `Android 4.4.2; SM-T531 Build/KOT49H`

**Comment by allisonmuise** [comment]
I had issues in the Android browser - The video would download rather than playing. On Chrome it worked well. I didn't notice that the video was slow to start, but I was also working on a local wifi network playing a video hosted on my desktop so that may have boosted performance :) 

The AGOL/Server teams are looking into this. It appears to be an issue with mp4s attached to both AGOL-hosted and Server services and is reproducible in the webmap so it seems unlikely that any fix will need to come from our side.

**Comment by allisonmuise** [comment]
verified
