### ISSUE TITLE
Manager throws TypeError when org basemap group is not Public

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#168]
When the group used to create a Manager app contains more than 1 map, and when the org basemap group is either Private or only shared with the Org, the app throws a TypeError in the console and refuses to load even when credentials are provided.

@MikeTschudi implemented a short-term fix for this that catches if the basemap group doesn't exist and uses the topo map instead. 

@CTLocalGovTeam  Could you please:
1) investigate why the app can't access content in a non-public basemap group even when valid credentials are provided

2) implement a fix that will be compatible with portal/disconnected portal implementations.

Please note that this issue does not need to be addressed immediately (note Milestone), but it will likely need to be addressed before the next full AGOL release in order to be included in the Portal 10.5 builds. We can discuss further next week.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @MikeTschudi 

The root cause for this issue is that while getting the basemap group's info the app was creating a new portal object instead of using the one already initialized by the boiler plate. The portal object created by boilerplate has complete information after the user has logged in. Since the app was creating a new portal object without using credentials, it did not have all the details and hence was failing even after signing in.

The temporary fix implemented by @MikeTschudi will not work in disconnected portal.

We feel the correct way to fix this is to use the boilerplate's portal instance. This will ensure everything will work as expected in connected as well as disconnected environment. 
* If the basemap group is private, and user **is not logged in**, the basemap will not be loaded. 
* If the basemap group is private, and user **is logged in**, the basemap will be loaded. 

Here is a screenshot of the required code changes

![basemaperror](https://cloud.githubusercontent.com/assets/2959186/16257315/65738a02-3875-11e6-8a4e-a5f44f12e403.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Thanks. 10.5 will be built from the 4.3 AGOL release, so we'll put this fix in then.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have implemented above fix & will deliver it in the next code release.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified on disconnected portal
