### ISSUE TITLE
Missing message on refresh in non-english languages

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#182]
Clicking the refresh button in english raises the browser warning "All selections and unsaved changes will be discarded"

Clicking that button in an arabic or french browser (only other languages tested) raises an empty browser prompt window.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We have fixed typo errors in few existing NLS keys(js/nls/resources.js) except files of other languages. This issue is due to the keys that is not changed in all other NLS files of other languages.

In this case typo error for "confirmManualRefeshText" key was fixed in(js/nls/resources.js), but in other files still it is pointing to incorrect key "confirmManualRefeshText" due to which message is missing in alert box.

We have also mentioned this in the "Note" section in Email dated 8-1-16 with Subject "Delivery for CrowdSource Manager AGOL 4.3 Sprint 2/2 (Enhancements & Bug fixes)".

Could you please change other NLS files by referring (js/nls/resources.js) & let us know if issue is still reproducible after this change.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Ah...that makes sense. Thanks!
