### ISSUE TITLE
BUG-000102247 App hangs when loading if visibility range set on layer

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#215]
When a layer is set with a visibility range that prevents any features from drawing at the scale the map is saved, Manager fails to load. It spins infinity without throwing any error messages in the console. The current workaround for this is to save the map zoomed in further.

The app should load following the pattern in Reporter: The table should populate, but the features shouldn't draw in the map.

(support case pending)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are analysing this ticket.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are not able to reproduce this issue. However, I recognised that the app was not honouring visibility range settings. We have made a fix for this if you would like the app to honour the visibility range. As of now with the current app the layer is visible irrespective of this settings.

Can you please share the app so that we can investigate it.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : here is a repro app: http://ess.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=5d79e921963c4ad7a90688ebcc357c4d

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have partially analysed this issue and found that it is somewhere related to security of layer, but we are not sure on it. So, we need some more time to fix it.

Please let me know if it works for you.  

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
That works for me, Pratik

**Comment by allisonmuise** [comment]
verified
