### ISSUE TITLE
No response on clicking a row in dataviewer . 

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#220]
App throws  a console error message: "Error: Layer does not support query capability."

This looks like a regression issue. Behavior is not seen in production. 

What is the LOE  and when can we get a fix.?

cc @allisonmuise

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @skrishn  

For fetching data on click of a row in dataviewer we use queryFeatures() which is an inbuilt method of FeatureLayer. We have analysed that this issue to is due to the queryFeatures() which is internally failing in
JS API 3.20 itself. It works fine with JS API 3.19 version.

For this, we created some samples which simply does a query of "1=1" using queryFeatures method of FeatureLayer. This sample does not contains any code related to CSM application.


[Sample containing JS API Ver. 3.20](https://jsfiddle.net/pratik_gohil/f527mz50/show/) - This sample will throw error in console as shown below

![image](https://cloud.githubusercontent.com/assets/2959186/23064418/04e6d300-f536-11e6-9a73-cd3ecd381fab.png)



[Sample containing JS API Ver. 3.19](https://jsfiddle.net/pratik_gohil/ewqe73ft/1/show/) - This sample will display a successful message once queryFeatures is completed

To conclude I think it has to do with the API itself and there is nothing we can do with our code to resolve this. Could you verify with the API team for this? or we will have to revert to 3.19 for this release.

--Pratik Gohil

**Comment by skrishn** [comment]
@CTLocalGovTeam 

Thanks.  JS API team is working on this issue.

cc @allisonmuise
