### ISSUE TITLE
 DojoConfig: Update apps to set async:true to avoid console warning

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#232]
In apps that create a web map the following warning appears in the console unless dojoConfig async is set to true.

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

Set to true in config apps to remove this warning (and the associated problems it warns about) from the app.

**Comment by allisonmuise** [comment]
1649

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

While analysing we observed that, in the latest code of the develop branch, async is already set to true in dojo configuration as shown below.

![image](https://user-images.githubusercontent.com/2959186/30746690-36bf2c32-9fc8-11e7-9bff-9c9cd717e96e.png)

Further, we also tested this by working with different web maps. However, we were not able to see the error(```[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.```) in the console.

Could you please provide us with the web map id for which error is getting logged in the console. So that it be would be helpful for us in troubleshooting it further.



--Pratik Gohil

**Comment by allisonmuise** [comment]
Per the request form the core team, setting async to true means that this message will not appear. IF it is already set correctly, there is no need for further work on this issue.
