### ISSUE TITLE
panel arrows don't show when header background color is white

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#239]
![image](https://user-images.githubusercontent.com/2752195/29232310-d935dc94-7e9f-11e7-8c5b-f0ac00a7e474.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

As per the current implementation, panel arrow buttons are always displayed in white and its background is as per the theme colour. Over here, since theme colour is also white we are unable to see the arrow button.

Hence, to overcome this we could consider alternate approaches as listed below

**Approach 1: When theme is in white colour, we would display arrow button in black as shown below**
![image](https://user-images.githubusercontent.com/2959186/30859379-0cb51ef8-a2e1-11e7-902a-6f85a92b5494.png)

**Approach 2: We could change the arrow button(.png) to fontillo icon, and set its colour as header text colour. Screenshots for the same is as shown below**

a. When header text colour is blue and theme colour is white
![image](https://user-images.githubusercontent.com/2959186/30859501-a8aa7c36-a2e1-11e7-9403-bbf469b3d206.png)


b. When header text colour is red and theme colour is in other colour(For e.g:- yellow)
![image](https://user-images.githubusercontent.com/2959186/30859680-56fdba14-a2e2-11e7-8f7d-2afe8b0417fc.png)

Please share your thoughts on this.



--Pratik Gohil

**Comment by allisonmuise** [comment]
Is there a difference in LOE for these two options? I'm slightly leaning towards Approach 2, but not if it's significantly more work.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

> Is there a difference in LOE for these two options? I'm slightly leaning towards Approach 2, but not if it's significantly more work.

LOE for both the approach is low. We could implement Approach 2 in this release.

Please confirm should we go ahead and implement Approach 2.


--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, please proceed with approach 2

**Comment by allisonmuise** [comment]
verified
