### ISSUE TITLE
Crowdsource Manager is not showing any records after the web map is saved in new map viewer

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#332]
**To Repro:**
1) Deploy Citizen Problem Reporter solution
2) Add a few records using Citizen Problem Reporter app
3) Open manager and notice the records are visible in table and map.
4) Open the Citizen Problem Manager map in new map viewer (not the classic viewer)
5)Save the map and refresh manager app and notice that the records are not visible anymore, no console error either.

![image](https://user-images.githubusercontent.com/10148401/147788027-3cef2904-521f-409c-8c14-00056375659b.png)

**Comment by aparveen** [comment]
@sumitzarkar Sorry I couldn't assign you the issue, so I assigned Ganesh instead

**Comment by sumitzarkar** [comment]
@aparveen 

We are analyzing this issue and we will share our findings soon

**Comment by sumitzarkar** [comment]
@aparveen 

We analyzed this issue and here are our findings:

- This issue is reproducible in both Reporter and Manager app.
- Reporter and Manager app have a WebmapList widget and it filters the webmap and layers based on some conditions like if the layer has capabilities and if the layer is visible or not. Based on such conditions it filters the webmaps to be shown /considered for use in the application.
- We found that whenever any webmap is saved using New Map Viewer it is not adding 'visibility' property and hence the app is considering no layer is visible 
- New Map Viewer is only adding 'visibility' property only when it is turned off
- For e.g. We turned off the Birds Observation layer from the New MapViewer
![image](https://user-images.githubusercontent.com/9443956/148031733-38b02639-ce09-4133-9501-79f000d5f690.png)

- However, we found that in the old map viewer we are able to get the 'visibility' property when the layer is turned on/off

We think this needs to be addressed in New Map Viewer, could you get AGOL team's input on this.

**Comment by aparveen** [comment]
Sent an email to AGOL team, will update the issue when I hear back
![image](https://user-images.githubusercontent.com/10148401/148265573-5588a39b-8ef6-4e20-9130-25f0d96f7b19.png)

**Comment by aparveen** [comment]
I heard from the AGOL team, this is an expected behavior with the new viewer - visibility is an optional property with an implicit default of true. We should look into the way to fix it from our side

**Comment by sumitzarkar** [comment]
@aparveen 

Ok, We can update the code which will take care of this behavior.

We need to fix this in both Reporter and Manager. So could you please create a separate ticket for the Reporter App as well?

**Comment by sumitzarkar** [comment]
@aparveen 

### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | Yes  |   | ​ Need to check with older Applications if any difference is observed in showing/hiding layers that are turned off /on from the webmap
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Runtime Impacts | Need to test following different cases:<ol><li>WebMap Create/updated with New Mapviewer</li><li>Webmap created/updated with old map viewer</li></ol>

**Comment by aparveen** [comment]
Verified in QA
