### ISSUE TITLE
Duplicate domain issue when the multiple domain applied to a field for each different subtype

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#348]
Test app: https://localdeployment.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=438aa4b393bd4650b5c741149ae2961e

When you click the filter for the domfield, you will see the same value reported multiple times separated by a comma. It seems this is happening because it has 3 different domains applied to this field for each different subtype. In the user’s case it is much more significant as they have more subtypes and domains.

![image](https://user-images.githubusercontent.com/10148401/183765616-3260adb4-774d-401e-9bb2-875921bcea0e.png)

Seeing this issue while filtering in the table, I don't see this issue during editing.

**Comment by aparveen** [comment]
@sumitzarkar could you please assess this issue? Thanks so much.

**Comment by sumitzarkar** [comment]
@aparveen 

We are able to reproduce this issue and we have found the root cause, we will fix this and deliver it in the next code drop.

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Test | Nee to test with Layers having typeid field

**Comment by skrishn** [comment]
verified in qa
