### ISSUE TITLE
change browser tab text

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#44]
While app loads, tab displays 'Constituent Engagement'. Until the app name can be retrieved, don't display anything.

**Comment by CTLocalGovTeam** [comment]
OK.  We will implement this in the next release.

**Comment by LindsayThomas** [comment]
Verified a Custom Name will appear in the Browser Tab.

@allisonmuise Note: The URL to the application ( http://computername/manager_06/?appid=c1270510f4c440129a3a0117e437d8c9) is displayed in Browser Tab initially. Once you click on a sign in option then you get the Custom Name in the browser tab. I *think* this is expected behavior with the application being hosted the way it is, other applications see to work that way. I am closing the issue but reopen if this isn't correct.

**Comment by ScottOppmann** [comment]
We should also validate that a shortcut icon is created when you place a link to the application on a tablet home screen.

Sent from Scott's iPhone
909-728-7082

On May 7, 2015, at 5:14 PM, Lindsay Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Verified a Custom Name will appear in the Browser Tab.

@allisonmuise<https://github.com/allisonmuise> Note: The URL to the application ( http://computername/manager_06/?appid=c1270510f4c440129a3a0117e437d8c9) is displayed in Browser Tab initially. Once you click on a sign in option then you get the Custom Name in the browser tab. I think this is expected behavior with the application being hosted the way it is, other applications see to work that way. I am closing the issue but reopen if this isn't correct.
