### ISSUE TITLE
display comments in details view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#46]
Display comments for a feature (using comment popup formatting) under the thumbnails in the item details view.

**Comment by allisonmuise** [comment]
Format as in Reporter

**Comment by CTLocalGovTeam** [comment]
OK.  We will implement this in the next release.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,
We wanted to confirm the UI mockup for displaying comments in manager app since the UI will be slightly different from the Reporter app. Please have a look and let us know if you have any comments.

----
![image](https://cloud.githubusercontent.com/assets/2959186/7565690/ac1ac77e-f80f-11e4-981c-ceb183ecbbea.png)

----
![image](https://cloud.githubusercontent.com/assets/2959186/7565709/cb12dd38-f80f-11e4-8331-43628d0a5023.png)

----
![image](https://cloud.githubusercontent.com/assets/2959186/7565711/d43e20d4-f80f-11e4-9b75-3c79a704c66a.png)

**Comment by allisonmuise** [comment]
If attachments are enabled, but none have been submitted, how will the UI look?

Please change 'Photos' to 'Attachments'

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, Ok, we will change 'Photos' to 'Attachments'.
If no attachments are submitted, and attachments are enabled, then it would look like the second mockup above. Current implementation is that the 'Attachments' section is not displayed at all when no attachments have been submitted. 

The reporter app on the other hand displays a message 'No attachments found' like this, since there is a dedicated button and panel to display attachments.
![image](https://cloud.githubusercontent.com/assets/2959186/7582466/811c3ca0-f8ab-11e4-940c-6847948429a0.png)

**Comment by allisonmuise** [comment]
ok. Thanks for the additional info.

**Comment by allisonmuise** [comment]
verified
