### ISSUE TITLE
Refresh button resets the current view of the application to Split View

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-manager#57]
Refresh button resets the current view of the application to Split View. User would probably expect that current view would persist after a refresh

Repro steps
-In Manager
-Set the application to Map View (or List View)
-Tap refresh
-Application will go back to split view

**Comment by allisonmuise** [comment]
This has been discussed with CT and the requested behavior would be a major development effort that could not be completed in the requested time frame along with the other assigned issues. I'll put this in the backlog.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Here are the scenarios we are considering to implement. Please confirm.

1. Application is in Map/Split/List View, user clicks refresh, retain the original View.
4. When the Details View is open in either Split View or Map View, user clicks refresh, the respective View will be retained, however since all selections/activations are lost, Details View will not be retained, it will display the map in place of Details View.
5. App is in Split View, and user resizes the table/map, user clicks refresh, retain the size of table/map.
6. App is in Show Selected Mode in any of the three Views, user clicks refresh, 
  * The View is retained, but the table is redrawn and scrolled to top 
  * Selections of rows/features are lost 
  * Selection Options button in top bar will be disabled (since there are no selections)
7. If any filter is active (using search icon in top bar), user clicks refresh, the filter will be retained 
  * If the filter does not return any rows after refresh, the table/map will display all rows
    * The search box will stay open and display "No results found"
  * If user switches to Show Selected Mode after a filter is applied, user clicks refresh, the filter is retained, but the selections are lost.
8. Sorting status of fields will be retained
9. Vertical scroll position will be retained
10. Horizontal scroll position will not be retained
11. Map extent will be retained
12. If a row is in edit mode, refreshing will not retain the edit mode for that row

Notes:
  * Selected rows and active row in table will not be retained since all layer data is fetched again
  * Feature selections on map will not be retained since all layer data is fetched and populated again
  * An alert message will be displayed as its done currently *(All changes/selections will be lost)*

**Comment by allisonmuise** [comment]
I have questions about 5 and 10:
5: 'The search box will stay open' : Do you mean that the search results box will re-open to display no results found'?

10: I believe that currently edits to the row are saved before the refresh. I'm ok with edit mode being discarded as long as the edits are kept.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Here is our response on the above. 

5: The search box will not re-open  to display "No results found". To simplify this further, we are thinking of providing this behavior
 * The searchbox will always be closed automatically (if open) after a refresh
 * It wont re-open even if no records are found after a refresh
 * User can click the Search icon anytime to see if a filter is active or not. It displays the placeholder text if no filter is active and displays the search text if a filter is active.

Please let us know if this is ok.

10: Thats correct. The edits will be saved.

**Comment by allisonmuise** [comment]
Yes, this sounds good. Please proceed.
----- Reply message -----

**Comment by allisonmuise** [comment]
verified
