### ISSUE TITLE
Android Tablet - Keyboard floats on top of Esri sign in dialog

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-manager#58]
Tested on Samsung Android Tablet (Galaxy 3)  - LandScape Mode

Repro Steps

Sign in to Esri in manager
Sign dialog pops up 
Android Keyboard will cover up the username and password textbox
Start typing, screen will move (now you can only see the username text box)
To type in the password, the user will have to tap the screen and drag the dialog into view.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please investigate this behavior and provide a description of (a) possible fix(es).

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @LindsayThomas,
This is the default behavior of Android OS. When sign in dialog is invoked, it already has the focus set on the username textbox. This is default behavior of identity manager. Due to this, as soon as you click on 'Sign in', the soft keyboard is displayed as the username textbox has focus. 
However, it gets overlaid by the keyboard and shifts into view after a keypress. On desktops, you can tab to the next textbox, but android keyboard do not provide a tab key. Hence, users have to drag the sign in dialog into view to enter the password. 

We don't see an elegant fix for this. We thought of pushing the sign in box a few pixels up, but this will likely be a device specific fix.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This is consistent with what I've experienced on other web sites on my own Android phone. I was hoping there was an elegant way around it, but if not let's leave the behavior as-is. 
Thanks for looking into it.
