### ISSUE TITLE
Cannot unselect features in 'Show Selected' view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#62]
Currently I cannot click the checkmarks to unselected features when in the 'Show Selected' view of the table. I should be able to unselect features in this view. Unselecting features should remove them from this view.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise This is as designed. In 'show selected' mode, the app does not allow any interaction with the table. This is because, the table used to update itself on every map pan/zoom and there were challenges in retaining the state of the table.
However, now that we have removed geographic filtering, we think this may be possible to implement. 
We will investigate this further and keep you posted.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We have been able to implement facility to remove selections when user is in 'Show Selected Mode'
Here are the highlights of this feature:

1. When user unselects an issue in 'Show Selected Mode', then the issue is removed from the list and the feature selection is also removed from map.
2. When user unselects all issues in 'Show Selected Mode', then the table resets to display all issues without any active/selected rows.
3. In 'Show Selected Mode', if user selects features from map, then the table updates to show the selected issue in table. Vice-versa, if user unselects feature from map, it is removed from table.
  * When user single clicks a feature on map, it is 'activated' and 'details' button is enabled. User can view its details, but the issue is not present in table, since it is only 'active' and not in selected state yet.
  * To select that feature, user can go back to map and click again to select that feature. It will be added to the table.
4. If user is viewing details of an issue in 'Show Selected Mode', if user unselects the active issue, then the details view is switched automatically to map view, without changing the extent of map.
5. Only selections are retained and 'Active' row is not retained when user switches between              
'all' - 'selected' - 'all' mode.

Please let us know if you have any comments on this.

**Comment by allisonmuise** [comment]
This sounds great! I can't think of any other scenarios to cover.

**Comment by allisonmuise** [comment]
verified
