### ISSUE TITLE
Cannot edit features in 'Show Selected' view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#63]
Editing is not available when viewing only selected features in the table.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise This is as designed. Editing is not available in selected mode.  
This was due to challenges in maintaining the state of selected records, editing, highlighting etc. when the app was designed to work with geographic filtering. When you pan/zoom the map, the table updates itself.
Now that we have removed geographic filtering, we think this may be possible to implement. 
We will investigate this further.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We have been able to implement editing of features in 'Show Selected Mode'. This will be delivered in the upcoming release.

**Comment by allisonmuise** [comment]
verified
