### ISSUE TITLE
App required reload to update list when map is filtered

### ISSUE THREAD

**Issue by clareprice** [Esri/crowdsource-manager#69]
@allisonmuise 

With the current ArcGIS Online version of the manager app, when a feature is edit in the list and the map is filtered by this edit, though the map will filter, the list will not filter and the selected bar still appears on the map. Reloading the app is required to view the updated list. See screenshot:
![image](https://cloud.githubusercontent.com/assets/5611508/8086593/053ecec0-0f4b-11e5-98fa-e56cc92f7b90.png)

**Comment by allisonmuise** [comment]
@clareprice I'm not clear on the issue you're seeing, but is this on prd, or devext? 

There are quite a few changes coming to this app in July. If what you're seeing is on prd, could you take a look at devext and see if it's still an issue?

**Comment by clareprice** [comment]
@allisonmuise This is an issue on devext as well. There is the refresh button now which means the entire web page does not need to be refreshed, but ideally when the map updated the list would as well.

**Comment by allisonmuise** [comment]
Moving this to the backlog as an earlier design decision was made to not update the table immediately after edits. We can look at this again if it becomes an issue.

Repro steps are: 
1) filter a layer in the map so that only some features are visible
2) Make the field used in the filter editable
3) Share the filtered map with a group that feeds a Manager app
4) In Manager, change the attributes of a feature so that they no longer meet the filter requirements.

This hides the feature in the map (although the selection graphic is still visible), but the record is still listed in the table.

Clicking refresh or re-sorting the table refreshes the table.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @clareprice 
We are thinking of the following approach to support this. Please let us know your thoughts.

* Query for the same row (honoring all definition expressions) after every edit
* If no result is returned, then remove row from the table

Everytime a field is updated, two requests will be done
1. To save the edit
2. To query the edit

**Comment by allisonmuise** [comment]
How will adding second query impact app performance?

**Comment by allisonmuise** [comment]
minimal impact per Dr. Anand on call. Please proceed with this approach

**Comment by allisonmuise** [comment]
verified
cc @clareprice
