### ISSUE TITLE
Auto hide layer/map picker after user selects a map and layer

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-manager#85]
Map and layer picker to become a floating panel on top of map/data grid to free up space and make the user experience cleaner.

**Comment by MikeMillerGIS** [comment]
Add a button or arrow to top bar to show panel.  After selection, panel auto hides.

**Comment by allisonmuise** [comment]
Map/layer selection panel draws on the left side of the screen under the header bar. Map/layer selection behavior is generally consistent with the current app, with the exception that the panel 'closes' when not in use. Panel can be opened/closed by clicking/tapping a tab on the right side of the panel.

(Image of this UI to follow. Description of actions below)

If the group contains more than one map:
- On app load, map & layer selection panel is open, partially covering the other app UI elements.
- Draw content from first map/layer, but disable/grey out all app UI elements other than the map/layer selection panel on initial load as no map/layer has been selected yet. User must choose map & layer to proceed. 
- On choosing a map with multiple layers, the layer list expands (current behavior)
- On choosing a layer or map with a single layer, panel slides closed to the left
- Panel slides open to the right when clicking on the arrow tab to allow selection of another map/layer. Other UI elements not disabled if panel is opened by clicking/tapping the arrow tab (not initial load).
- If panel was opened by clicking the arrow tab (not initial load) panel can be closed by selecting a map/layer, clicking the arrow tab, or by interacting with any of the other app UI elements.

If the group contains one map with multiple editable layers:
- On app load, map & layer selection panel is open, partially covering the other app UI elements. Map item is 'opened' to show the list of layers.
- Draw content from first layer, but disable/grey out all app UI elements other than the layer selection panel on initial load as no layer has been selected yet. User must choose layer to proceed. 
- Clicking the map tile collapses/expands the layer list (current behavior)
- On choosing a layer, panel slides closed to the left
- Panel slides open to the right when clicking on the arrow tab to allow selection of another layer. Other UI elements not disabled if panel is opened by clicking/tapping the arrow tab (not initial load).
- If panel was opened by clicking the arrow tab (not initial load) panel can be closed by selecting a layer, clicking the arrow tab, or by interacting with any of the other app UI elements.

If the group contains a single map with a single editable layer:
- On app load, do not open the map/layer selection panel. It should load collapsed, but be expandable by clicking/tapping the arrow tab so that users can still access the map information if needed.
- Draw layer content immediately on load. Do not disable/grey out app UI elements - there is only one layer so it should load and be responsive immediately.
- If panel was opened by clicking the arrow tab panel can be closed by selecting the map, clicking the arrow tab, or by interacting with any of the other app UI elements.

**Comment by allisonmuise** [comment]
cc @ddred12

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

> If the group contains more than one map:
> Draw content from first map/layer, but disable/grey out all app UI elements other than the map/layer selection panel on initial load as no map/layer has been selected yet. User must choose map & layer to proceed.

* Do we need to disable the table, map, timeslider and popup details panel or just the buttons displayed in top bar(including sign-in)?
* Since layer selection is mandatory on load to proceed, do we need to disable the arrow button to collapse map/layer selection panel?
* When user signs in, we think that we should retain the state of map/layer selection panel, i.e., if it was open, it will stay open and vice versa. Correct?

> If panel was opened by clicking the arrow tab (not initial load) panel can be closed by selecting a map/layer, clicking the arrow tab, or by interacting with any of the other app UI elements.

* Does other app UI elements include table, map, popup details, or just the buttons(refresh, search, filter,help, signin)  in top bar?

>  One map with multiple editable layers:

* Map item is expanded to show list of layers. The default layer is loaded, and is displayed in bold in map/layer selection panel. With app UI elements disabled on load, if user wants to continue with default layer then he will have to click the layer (already displayed in bold) to continue. Just wanted to confirm if this is ok.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

> Do we need to disable the table, map, timeslider and popup details panel or just the buttons displayed in top bar(including sign-in)?

Everything but the sign in and map selection panel should be disabled. I imagine this something like what you do for the current help window in Reporter where the 'inactive' parts of the screen are all greyed out.

> Since layer selection is mandatory on load to proceed, do we need to disable the arrow button to collapse map/layer selection panel?

Layer selection is only mandatory because i think that was a technical limitation of loading the app. If it's not, the first layer doesn't need to load. Regardless, yes please disable the arrow button on load.

>When user signs in, we think that we should retain the state of map/layer selection panel, i.e., if it was open, it will stay open and vice versa. Correct?

Yes, this is a good idea.

>Does other app UI elements include table, map, popup details, or just the buttons(refresh, search, filter,help, signin) in top bar?

Yes, the map, table, etc as well as the header elements

>Map item is expanded to show list of layers. The default layer is loaded, and is displayed in bold in map/layer selection panel. With app UI elements disabled on load, if user wants to continue with default layer then he will have to click the layer (already displayed in bold) to continue. Just wanted to confirm if this is ok.

See above. Is there a technical limitation that forces us to load something into the map/table/details spaces on app load, or was this a requirement of the previous design because it looked funny if nothing was loaded? If it's the latter, let's not load anything until a map & layer have been selected.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The limitation is that the map container needs a webmap to spin itself up. This is the reason we are auto-loading the first layer of the first webmap. If we decide not to auto-load, an alternative is to display a map with just the first basemap available in the Org. Otherwise, we will have to display three empty boxes (table, details, map) to the right of map/layer selection panel. Once user selects a map/layer, it will load that webmap and layer in that map container and start to display rows in the table.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Since we want users to select something before beginning, let's go with an empty table, empty details area, and the basemap only in the map area.

**Comment by allisonmuise** [comment]
On app load (minus the loaded content per previous discussion):
![picture1](https://cloud.githubusercontent.com/assets/2752195/12792035/c054058a-ca5e-11e5-90ec-1d831f5ee301.png)

After layer selection:
![picture3](https://cloud.githubusercontent.com/assets/2752195/12792053/d6feb230-ca5e-11e5-9311-648036218825.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Some questions on the mockups,  

1. The map/layer selection panel is always to be displayed as an overlay in the app, i.e., it will overlap the table and details panel. The map, table and details panel wont resize when the map/layer selection panel is opened. Correct?
2. The timeslider is displayed only for time-enabled layers. The bar containing the timeslider will be hidden and the table and map will fill up that available space for non time-aware layers. Correct?
3. The feature layer table is currently built on a third party control called [datatable](http://datatables.net/). This is a jQuery plugin. We used this, as it is a robust table drawing plugin and offers a lot of functionality like sorting, filtering, pagination, selections, RTL support etc. and is future proof. We see that the styling specs in ppt recommends to use the plain bootstrap Bordered table with calcite css overrides for displaying the feature table. While this will significantly improve performance as it is lightweight, it will also increase dev efforts as we have to build each feature into it like sorting and filtering. Just wanted to confirm if the recommendation to use bootstrap bordered table with calcite overrides is to be considered final.
4. We see there are two calcite css frameworks available, [calcite-web](http://esri.github.io/calcite-web/) and [calcite-bootstrap](http://esri.github.io/calcite-bootstrap/), can you please confirm which one is to be used?

**Comment by allisonmuise** [comment]
>The map/layer selection panel is always to be displayed as an overlay in the app, i.e., it will overlap the table and details panel. The map, table and details panel wont resize when the map/layer selection panel is opened. Correct?

Correct

>The timeslider is displayed only for time-enabled layers. The bar containing the timeslider will be hidden and the table and map will fill up that available space for non time-aware layers. Correct?

Correct

>While this will significantly improve performance as it is lightweight, it will also increase dev efforts as we have to build each feature into it like sorting and filtering.

Ideally, I would like to go with the calcite table. It's lightweight and looks closest to the new ops dashboard and soon tables throughout AGOL. 
That being said:
- In your opinion, how does the gain in performance compare to the risk associated with building in the filtering and sorting functions manually?
- I have no concept of the time required to do the work outlined in these issues.  Would having to use the calcite table jeopardize the ability to get this project completed in time to make the June release of AGOL?
- Can the Calcite formatting be applied to the current table?

>We see there are two calcite css frameworks available, calcite-web and calcite-bootstrap, can you please confirm which one is to be used?

Please use calcite-bootstrap for the app. I believe calcite-web is the css for Esri's documentation pages.

**Comment by CTLocalGovTeam** [comment]
> In your opinion, how does the gain in performance compare to the risk associated with building in the filtering and sorting functions manually?  

The gain in performance will be significant as compared to the risk in building the filtering and sorting manually. 

> I have no concept of the time required to do the work outlined in these issues. Would having to use the calcite table jeopardize the ability to get this project completed in time to make the June release of AGOL?

No. We will be able to meet June release with the calcite table too.

> Can the Calcite formatting be applied to the current table?

Though this can be done, it will be difficult to achieve and maintain further

Our additional thoughts on this are that even with the current table, it is anyway going to require substantial dev time for adding the filtering and 'customizing' the sorting functionality. We will keep investigating and weigh our options further.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Ok, based on the above, I am leaning towards proceeding with the Calcite+Bootstrap table. Please let me know if you run into any other potential issues and we can re-evaluate.

**Comment by allisonmuise** [comment]
verified
