### ISSUE TITLE
Filter map and table by time

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#98]
AGOL maps can be configured to display only features found withing a configurable, adjustable time frame. Expose this time filtering functionality in the application to allow review of incidents from particular time windows. Configuration for this setting will be done in the web map.

Use case examples: review outstanding incidents in 1 week blocks, review incidents submitted in the past 24 hours.

Graphic of the UI for this widget will be provided.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The default behavior of the app is to load all features from layer in table and map. When a time window is applied, do we need to filter rows in table in addition to features on map? or do we continue showing all rows in the table?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : The idea is to filter both the table and the map. I don't think the playback functionality is necessary in this app - just the filtering aspect of the time slider. Is possible to separate the two functions and implement only the filtering?

**Comment by allisonmuise** [comment]
![picture3](https://cloud.githubusercontent.com/assets/2752195/12792118/2ce715d4-ca5f-11e5-9775-1a3564d5043c.png)
see ppt sent via email for additional details re: styling

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Yes, it is possible to remove playback animation controls and implement only filtering.

1. Does the time labels displayed below the two thumbs on the slider, need to move along with the thumb as shown in the mockup? Because, when the thumbs are very close to each other, the time labels may overlap.
ArcGIS Online Map Viewer displays the time labels in a fixed place as shown below.
![image](https://cloud.githubusercontent.com/assets/2959186/12818083/4d2de300-cb7b-11e5-96dc-89c414738ca8.png)
2. When the details panel is in edit mode, and user changes the time extent, such that the selected feature is not within the time extent, do we reset the details panel without any message? How do we handle this?
3. When filters are applied in the fields of feature table(ask for values) and/or using the 'Search' icon in top bar and user changes the time extent, the app needs to honor all three, the Search filter, Field filter as well as the time extent. Correct?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

>Does the time labels displayed below the two thumbs on the slider, need to move along with the thumb as shown in the mockup?

IMO the AGOL viewer's labels are more helpful in playback than in setting a specific range, but you make a good point about squishing together labels on the handles. Could we put a single label under the time slider that says *(start datetime)* to *(end datetime)* and updates as the handles are moved?

>When the details panel is in edit mode, and user changes the time extent, such that the selected feature is not within the time extent, do we reset the details panel without any message? How do we handle this?

Can filtering via attributes and time be disabled when that panel is in edit mode? Under these circumstances it would be helpful to provide a message along the lines of 'filters cannot be modified while editing is in progress' if someone tries to interact with the slider of attribute filters.

>When filters are applied in the fields of feature table(ask for values) and/or using the 'Search' icon in top bar and user changes the time extent, the app needs to honor all three, the Search filter, Field filter as well as the time extent. Correct?

Correct

**Comment by CTLocalGovTeam** [comment]
> Could we put a single label under the time slider that says (start datetime) to (end datetime) and updates as the handles are moved?

Yes. Center aligned below the slider?

> Can filtering via attributes and time be disabled when that panel is in edit mode?

Yes. we can disable search filter, attribute filters and time slider and display a helpful message.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : sounds good. Thanks.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

AGOL Map Viewer allows users to disable time animation as shown in graphic below. So, if its disabled for a layer in webmap, we do not show the time slider in Manager app for that layer. Correct?

![image](https://cloud.githubusercontent.com/assets/2959186/13005609/05b34eaa-d1a9-11e5-84b5-5627d5cdb584.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This is correct.

**Comment by allisonmuise** [comment]
verified
