### ISSUE TITLE
Filter map and table by attribute values

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#99]
Layers in AGOL maps can be configured to filter features using end-user specified values on one or several configured fields.

Expose these 'Ask for values' filters in MAnager to allow users to filter the map and table to only features with specific values.

Filters should honor prompts, hints, and other filter settings set in the map.

Multiple filters should be cumulative. For example, if two filters are applied (Field1 = 'A' and Field2 = 'B'), displayed records/features must meet both criteria.

Graphic of filtering UI will be provided.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We wanted to confirm if the ability to design/create a filter is to be provided in the Manager app, or that the app is expected to only display these filters in the Manager app.

The 'Create' tab is used to design and apply filters in the webmap. Are we expected to provide this facility in the manager app as shown in the screengrab below?
![image](https://cloud.githubusercontent.com/assets/2959186/12746031/ae11b2b0-c9c2-11e5-9a55-5b4000548bec.png)

OR, we only need the 'Change' tab that is used to modify values of filter items that 'Ask for values'. 
![image](https://cloud.githubusercontent.com/assets/2959186/12746083/f2ab28de-c9c2-11e5-975e-b8a73aa24e9b.png)

Do we need to provide the 'Edit' tab that allows you modify/add expressions to the filter? 
How about webmaps that do not have any filters defined in them? Will the filter option be disabled?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Manager will only display filters that have been set in the web map - essentially the content on the Change tab.

**Comment by allisonmuise** [comment]
![picture6](https://cloud.githubusercontent.com/assets/2752195/12792186/7c142ae8-ca5f-11e5-82c9-b588924745fd.png)
see ppt sent via email for additional details re: styling

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

1. Only filters that are set to 'ask for values' in webmap are to be displayed. Correct?
2. Our understanding of the mockup is that filters are to be displayed for each field separately. It's possible that the same field is used multiple times, then in such case, the filtering options will contain multiple items. How about cases where a large number of filters are set using a single field?. Need to think about how we handle this. Do we display a scroll bar?
3. The sort icon for fields is always displayed by default, do we display the filter icon only when a filter is applied (sort icon displayed by default), or always for those fields who have filter options set in webmap? This is because when you design a filter in webmap, it always has a default value and it is applied.
4. There can be three types of filter inputs, textbox, dropdown and a date picker. How will a filter be applied, since there is no button to click 'apply'? Enter text to filter and focus out? Select an item from dropdown or date picker?
5. When filter input is a text box, the ArcGIS Online Map Viewer does not allow you to empty the contents of text box and apply filter. The same case in Manager app, when user clears the contents of the input text box, do we display a message? or display the last entered value?
5. How can the user remove a filter that is applied?
5. The icon for ascending and descending sort will be replaced with the filter icon, thus the user loses the visual cue that a field is sorted as well as filtered. Is this ok?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

>Only filters that are set to 'ask for values' in webmap are to be displayed. Correct?

Correct

>Our understanding of the mockup is that filters are to be displayed for each field separately. It's possible that the same field is used multiple times, then in such case, the filtering options will contain multiple items. How about cases where a large number of filters are set using a single field?. Need to think about how we handle this. Do we display a scroll bar?

Yes, I'm good with a scroll bar. How about if the window expands to a % of the current screen height and then a scroll bar appears?

>The sort icon for fields is always displayed by default, do we display the filter icon only when a filter is applied (sort icon displayed by default), or always for those fields who have filter options set in webmap? This is because when you design a filter in webmap, it always has a default value and it is applied.

Display the filter icon only when an 'Ask for values' filter has been applied. The filter icon should not be displayed if there is no filter, if the filter is not used, or if the filter is a static filter applied in the web map and not accessible through Manager (aka 'ask for values' not set)

>There can be three types of filter inputs, textbox, dropdown and a date picker. How will a filter be applied, since there is no button to click 'apply'? Enter text to filter and focus out? Select an item from dropdown or date picker?

I only see a way to do drop down and text input filters as 'ask for values'. That option seems to be disabled for date fields. Are you seeing this capability? I suggest applying the filter on change of focus (could be the next filter parameter, could be clicking elsewhere in the UI to close the filter window. What do you think?

>When filter input is a text box, the ArcGIS Online Map Viewer does not allow you to empty the contents of text box and apply filter. The same case in Manager app, when user clears the contents of the input text box, do we display a message? or display the last entered value?

I will get back to you on this.

>How can the user remove a filter that is applied?

I will get back to you on this

>The icon for ascending and descending sort will be replaced with the filter icon, thus the user loses the visual cue that a field is sorted as well as filtered. Is this ok?

Yes, this is ok. We are modelling this behavior on Microsoft Excel which also gives no indication of the sorted fields or sorting direction.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

@MikeMillerGIS and I discussed the fact that, in order to create a filter in AGOL, a default filter value must be applied, and the filters cannot be fully cleared. Could you let us know if the following would be possible?

- Add a check box parameter to the configuration file that allows users to turn off the default filter values on app load. This parameter should be enabled by default so that, by default, the web map's filter settings are honored. 

- When this config parameter is disabled, the app will load to show all features in all layers that are not excluded by other means, such as a static filter. The default filter values will not appear in the filter panels.

- Add a 'Clear' button beside each active filter that allows that filter to be cleared, regardless of the configuration parameter setting.

**Comment by CTLocalGovTeam** [comment]
> How about if the window expands to a % of the current screen height and then a scroll bar appears?

Yes.

> Display the filter icon only when an 'Ask for values' filter has been applied. 

Sorry for asking this again. Do we display the filter icon only when a user applies the filter by changing the default value in the app? Or display the icon on app load, since the filter has a default value and is already in effect?

> That option seems to be disabled for date fields. Are you seeing this capability?

This works with date fields. Please see below.
![image](https://cloud.githubusercontent.com/assets/2959186/12845465/12dc032e-cc2c-11e5-9604-184709c754af.png)

>  I suggest applying the filter on change of focus (could be the next filter parameter, could be clicking elsewhere in the UI to close the filter window. What do you think?

Focus out is ok. It's also the current implementation for saving edits in the table.

> @MikeMillerGIS and I discussed the fact that, in order to create a filter in AGOL, a default filter value must be applied, and the filters cannot be fully cleared. 
* Add a check box parameter to the configuration file that allows users to turn off the default filter values on app load. This parameter should be enabled by default so that, by default, the web map's filter settings are honored.
* When this config parameter is disabled, the app will load to show all features in all layers that are not excluded by other means, such as a static filter. The default filter values will not appear in the filter panels.
* Add a 'Clear' button beside each active filter that allows that filter to be cleared, regardless of the configuration parameter setting.

Actually, we figured out a way to clear filters, even though they cannot be fully cleared in AGOL Viewer. Here's how we can do it:

1. Always honor the filters set in webmap
2. Provide an option to toggle (enable/disable) each filter for a field. Please see below.
![image](https://cloud.githubusercontent.com/assets/2959186/12845860/c57db890-cc2e-11e5-8175-824f8159141e.png)
![image](https://cloud.githubusercontent.com/assets/2959186/12845872/e8a90950-cc2e-11e5-88c0-6c26fe5411d8.png)

3. If a filter is disabled, then we can alter the definition expression of the webmap to exclude that part of the filter.
4. Do we still need the ability to configure filter behavior in configuration panel?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

The questions above are all related so I will answer them together:

Yes, let's still add a parameter to the configuration panel that will control how if filters are loaded when the app initializes. 

The user scenario here is: A large number of fields have a large number of filters available. When the app loads, if all these filters are applied there may not be any visible features. The user will need to go clear all the filters manually in order to see the data. They may then need to go reset some of the filters based on the information they see in the full dataset.

By un-checking the config parameter, the app will load with all filters cleared so that users don't need to clear all the filters to see the data. Under these circumstances, the filter icon wouldn't show in the field header because the filters aren't applied.

When the parameter is checked, the app would load with all filters active with their default values. In this case, the filter icon would display for all filtered fields on load.

Instead of the toggle, which some users may confuse with an 'apply' action, could the 'clear' be a simple X that is grey (inactive) when the filter is cleared and red (active) when there is a value? Clicking the red X would clear the current value. Please let me know if clearing this value is a technical issue.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

> Instead of the toggle, which some users may confuse with an 'apply' action, could the 'clear' be a simple X that is grey (inactive) when the filter is cleared and red (active) when there is a value? Clicking the red X would clear the current value. Please let me know if clearing this value is a technical issue.

Yes, Instead of toggle we can add clear button as a simple X

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Thanks. Was the rest of the explanation clear? I am traveling today and won't be on the call. Let me know if you'd like to set something up later in the week to discuss.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

When filter parameter is unchecked in configuration panel, we understand that the fields will not display a filter icon on load and all filters asking for values, as set in the webmap will be ignored on load. 
In this case, do we display the filter options for each field in inactive state on load, and let the user activate a filter later?,  OR does the unchecking in configuration panel mean that filters (which ask for values) set in webmap will be completely ignored and never show up for any field in the app?

The sort and filter options are displayed when user clicks on the 'menu' icon in each field. We are calling this the 'menu' icon because it displays a menu with options to sort and filter. Since this is a menu icon, we cannot use this to indicate the sorting order if sorting is applied by flipping it vertically. 
We are thinking of showing an arrow just beside the menu icon as a visual cue to indicate if sorting is active on a field. Do we need this? Please let us know your thoughts.
![image](https://cloud.githubusercontent.com/assets/2959186/13004697/f79cc0c2-d1a2-11e5-8e52-9c5565ea62e1.png)

In a scenario where user clears all filters applied on a field by clicking the X icon, do we replace the filter icon with the menu icon?

**Comment by allisonmuise** [comment]
>In this case, do we display the filter options for each field in inactive state on load, and let the user activate a filter later?

Yes

>does the unchecking in configuration panel mean that filters (which ask for values) set in webmap will be completely ignored and never show up for any field in the app?

No

>We are thinking of showing an arrow just beside the menu icon as a visual cue to indicate if sorting is active on a field. Do we need this?

Since we are modelling this experience after Excel, I'm gong to say that we don't need a sort order indicator. Excel doesn't show one and we have very little space to work with.

>In a scenario where user clears all filters applied on a field by clicking the X icon, do we replace the filter icon with the menu icon?

Yes, if no filters are applied, show the menue drop down arrow instead of the filter icon.

**Comment by allisonmuise** [comment]
verified. separate tickets will be opened for specific issues
